// 1. Create Students (6 nodes)
MERGE (s1:Student {id: "S01", name: "Aarav Sharma", level: "Beginner"})
MERGE (s2:Student {id: "S02", name: "Elena Rostova", level: "Intermediate"})
MERGE (s3:Student {id: "S03", name: "Chen Wei", level: "Advanced"})
MERGE (s4:Student {id: "S04", name: "Maya Patel", level: "Intermediate"})
MERGE (s5:Student {id: "S05", name: "Liam O'Connor", level: "Beginner"})
MERGE (s6:Student {id: "S06", name: "Zara Khan", level: "Advanced"})

// 2. Create Mentors (3 nodes)
MERGE (m1:Mentor {id: "M01", name: "Dr. Alicia Vance", field: "Graph Data Science"})
MERGE (m2:Mentor {id: "M02", name: "David Kim", field: "Cloud Infrastructure"})
MERGE (m3:Mentor {id: "M03", name: "Sarah Jenkins", field: "Full-Stack Development"})

// 3. Create Courses (3 nodes)
MERGE (c1:Course {code: "CS101", title: "Neo4j & Knowledge Graphs", credits: 4})
MERGE (c2:Course {code: "CS102", title: "Full-Stack Python APIs", credits: 3})
MERGE (c3:Course {code: "CS103", title: "Distributed Cloud Architectures", credits: 4})

// 4. Create Skills (4 nodes)
MERGE (sk1:Skill {name: "Cypher", category: "Database"})
MERGE (sk2:Skill {name: "Python", category: "Language"})
MERGE (sk3:Skill {name: "Docker", category: "DevOps"})
MERGE (sk4:Skill {name: "GraphQL", category: "API"})

// 5. Create Projects (3 nodes)
MERGE (p1:Project {id: "P01", name: "Enterprise Graph Engine", difficulty: "High"})
MERGE (p2:Project {id: "P02", name: "E-Commerce Recommender", difficulty: "Medium"})
MERGE (p3:Project {id: "P03", name: "Cloud Container Deployer", difficulty: "High"})

// 6. Create Companies (3 nodes)
MERGE (co1:Company {id: "C01", name: "GraphTech Labs", location: "San Francisco"})
MERGE (co2:Company {id: "C02", name: "NextGen Cloud", location: "Berlin"})
MERGE (co3:Company {id: "C03", name: "DataFlow Systems", location: "Bengaluru"})

// 7. Relationships: Mentors -> Courses (TEACHES)
MERGE (m1)-[:TEACHES]->(c1)
MERGE (m2)-[:TEACHES]->(c3)
MERGE (m3)-[:TEACHES]->(c2)

// 8. Relationships: Courses -> Skills (TEACHES_SKILL)
MERGE (c1)-[:TEACHES_SKILL]->(sk1)
MERGE (c1)-[:TEACHES_SKILL]->(sk2)
MERGE (c2)-[:TEACHES_SKILL]->(sk2)
MERGE (c2)-[:TEACHES_SKILL]->(sk4)
MERGE (c3)-[:TEACHES_SKILL]->(sk3)

// 9. Relationships: Students -> Courses (ENROLLED_IN)
MERGE (s1)-[:ENROLLED_IN {enrolledOn: "2026-01-10"}]->(c1)
MERGE (s2)-[:ENROLLED_IN {enrolledOn: "2026-01-12"}]->(c1)
MERGE (s2)-[:ENROLLED_IN {enrolledOn: "2026-02-01"}]->(c2)
MERGE (s3)-[:ENROLLED_IN {enrolledOn: "2026-01-15"}]->(c3)
MERGE (s4)-[:ENROLLED_IN {enrolledOn: "2026-02-10"}]->(c2)
MERGE (s5)-[:ENROLLED_IN {enrolledOn: "2026-03-01"}]->(c1)
MERGE (s6)-[:ENROLLED_IN {enrolledOn: "2026-01-20"}]->(c3)

// 10. Relationships: Students -> Projects (BUILT)
MERGE (s1)-[:BUILT]->(p2)
MERGE (s2)-[:BUILT]->(p1)
MERGE (s3)-[:BUILT]->(p3)
MERGE (s6)-[:BUILT]->(p1)

// 11. Relationships: Projects -> Skills (USES)
MERGE (p1)-[:USES]->(sk1)
MERGE (p1)-[:USES]->(sk2)
MERGE (p2)-[:USES]->(sk2)
MERGE (p2)-[:USES]->(sk4)
MERGE (p3)-[:USES]->(sk3)

// 12. Relationships: Students -> Companies (INTERESTED_IN)
MERGE (s1)-[:INTERESTED_IN {priority: "High"}]->(co1)
MERGE (s2)-[:INTERESTED_IN {priority: "Medium"}]->(co1)
MERGE (s3)-[:INTERESTED_IN {priority: "High"}]->(co2)
MERGE (s6)-[:INTERESTED_IN {priority: "High"}]->(co3);